package quarto.swing;

/**
 *
 * @author Steve Cances <steve.cances@gmail.com>
 */
public class Main extends javax.swing.JFrame {

	/**
	 * Creates new form Main
	 */
	public Main() {
		this.initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	private void initComponents() {

		this.menuBar = new javax.swing.JMenuBar();
		this.fileMenu = new javax.swing.JMenu();
		this.openMenuItem = new javax.swing.JMenuItem();
		this.saveMenuItem = new javax.swing.JMenuItem();
		this.saveAsMenuItem = new javax.swing.JMenuItem();
		this.exitMenuItem = new javax.swing.JMenuItem();
		this.editMenu = new javax.swing.JMenu();
		this.cutMenuItem = new javax.swing.JMenuItem();
		this.copyMenuItem = new javax.swing.JMenuItem();
		this.pasteMenuItem = new javax.swing.JMenuItem();
		this.deleteMenuItem = new javax.swing.JMenuItem();
		this.helpMenu = new javax.swing.JMenu();
		this.contentsMenuItem = new javax.swing.JMenuItem();
		this.aboutMenuItem = new javax.swing.JMenuItem();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		this.fileMenu.setMnemonic('f');
		this.fileMenu.setText("File");

		this.openMenuItem.setMnemonic('o');
		this.openMenuItem.setText("Open");
		this.fileMenu.add(this.openMenuItem);

		this.saveMenuItem.setMnemonic('s');
		this.saveMenuItem.setText("Save");
		this.fileMenu.add(this.saveMenuItem);

		this.saveAsMenuItem.setMnemonic('a');
		this.saveAsMenuItem.setText("Save As ...");
		this.saveAsMenuItem.setDisplayedMnemonicIndex(5);
		this.fileMenu.add(this.saveAsMenuItem);

		this.exitMenuItem.setMnemonic('x');
		this.exitMenuItem.setText("Exit");
		this.exitMenuItem.addActionListener(evt -> Main.this.exitMenuItemActionPerformed(evt));
		this.fileMenu.add(this.exitMenuItem);

		this.menuBar.add(this.fileMenu);

		this.editMenu.setMnemonic('e');
		this.editMenu.setText("Edit");

		this.cutMenuItem.setMnemonic('t');
		this.cutMenuItem.setText("Cut");
		this.editMenu.add(this.cutMenuItem);

		this.copyMenuItem.setMnemonic('y');
		this.copyMenuItem.setText("Copy");
		this.editMenu.add(this.copyMenuItem);

		this.pasteMenuItem.setMnemonic('p');
		this.pasteMenuItem.setText("Paste");
		this.editMenu.add(this.pasteMenuItem);

		this.deleteMenuItem.setMnemonic('d');
		this.deleteMenuItem.setText("Delete");
		this.editMenu.add(this.deleteMenuItem);

		this.menuBar.add(this.editMenu);

		this.helpMenu.setMnemonic('h');
		this.helpMenu.setText("Help");

		this.contentsMenuItem.setMnemonic('c');
		this.contentsMenuItem.setText("Contents");
		this.helpMenu.add(this.contentsMenuItem);

		this.aboutMenuItem.setMnemonic('a');
		this.aboutMenuItem.setText("About");
		this.helpMenu.add(this.aboutMenuItem);

		this.menuBar.add(this.helpMenu);

		this.setJMenuBar(this.menuBar);

		final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 945, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 417, Short.MAX_VALUE)
				);

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	private void exitMenuItemActionPerformed(final java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}// GEN-LAST:event_exitMenuItemActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(final String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (final javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (final ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (final javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem contentsMenuItem;
	private javax.swing.JMenuItem copyMenuItem;
	private javax.swing.JMenuItem cutMenuItem;
	private javax.swing.JMenuItem deleteMenuItem;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem openMenuItem;
	private javax.swing.JMenuItem pasteMenuItem;
	private javax.swing.JMenuItem saveAsMenuItem;
	private javax.swing.JMenuItem saveMenuItem;
	// End of variables declaration//GEN-END:variables

}
